blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/SpreadSheets600/exam-countdown-extension#readme
    about: Check the README for usage instructions and FAQs
  - name: 💬 Discussions
    url: https://github.com/SpreadSheets600/exam-countdown-extension/discussions
    about: Start a discussion for general questions or ideas
